### ISSUE TITLE
Flashing without cutting traces

### ISSUE THREAD

**Issue by hipposen** [octal-ip/ESP07_Growatt_SPF_3500-5000_ES_Monitor#1]
Hello,
i just wanna say thank for your great work.
i managed to flash it even without cutting or desolder the serial-chip.

i used a CP2102 Adapter only connect GND,RX,TX 
and for flashing the first time shorting gnd and gpio.

the dongle it self was powered via USB.

after this flashing via OTA works.

**Comment by octal-ip** [comment]
Thanks for letting me know, I've ordered a CP2102 to test this out. It might be more tolerant to interference from the SP3232 than the other UART chips I tried. I'll update the README with this tip if I can reproduce it, as this is a far easier option than modifying the board.

**Comment by octal-ip** [comment]
I've tested and confirmed that the CP2102 will flash the dongle without any modifications, this is a far better option than removing the SP3232. I've updated README.md to include this information. Thanks for your contribution @hipposen.

**Comment by RoganDawes** [comment]
Sorry to necro this thread, but I wanted to share the approach that I used, which was a lot better (in my mind) than trying to fight against the transceiver - Just use a USB-RS232 adapter instead of -TTL, and connect *through* the RS232 transceiver. I wrote it up here: https://powerforum.co.za/topic/32073-growatt-shinewifi-f-reflashed-with-esphome, along with a more comprehensive hardware mapping than I have seen elsewhere (including the button, the real time clock, and the SPI flash chip), and an example ESPHome configuration.
